trigger:
- master

pool:

  vmImage: "vs2017-win2016"

steps:

- task: UiPathInstallPlatform-preview@2

- task: UiPathTest@2
  inputs:
    testTarget: 'TestSet'
    testSet: 'Loan Processing'
    orchestratorConnection: 'Orchestrator'
    testProjectPath: 'UiBank_RPA Testing/project.json'
    folderName: 'Demo Day/RPA Testing'
    testReportDestination: '$(Build.ArtifactStagingDirectory)\Output\result.xml'

- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 
    outputType: 'Process'
    orchestratorConnection: 'Orchestrator'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'


- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'Orchestrator'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Demo Day/RPA Testing'


