trigger:
- master

pool:

  vmImage: "vs2017-win2016"

steps:

- task: UiPathInstallPlatform-preview@2



- task: UiPathTest@2
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'Cloud Orchestrator'
    testSet: 'ADO'
    folderName: 'Modern Folder'
    testReportDestination: 'output.xml'